autocnet/matcher/outlier_detector.py, autocnet/matcher/subpixel.py, docs/conf.py, docs/library/matcher/index.rst, docs/library/matcher/outlier_detector.rst, docs/library/matcher/subpixel.rst, docs/references.rst, functional_tests/test_two_image.py
Added adaptive_non_max_suppression, which will compute and return a mask for the keypoint list we have stored as an attribute for each node. The mask will have 1's in the places of the top n maximum minimum distances to another point that is significantly stronger. See http://graphics.cs.cmu.edu/courses/15-463/2005_fall/www/Papers/MOPS.pdf for more information.
=> Added adaptive non-maximal suppression. Fixes JIRA #71

autocnet/graph/network.py, autocnet/graph/tests/test_network.py, autocnet/matcher/outlier_detector.py, autocnet/matcher/subpixel.py, docs/conf.py, docs/library/matcher/index.rst, docs/library/matcher/outlier_detector.rst, docs/library/matcher/subpixel.rst, docs/references.rst, functional_tests/test_two_image.py
This is a start toward JIRA #31: "As a control network, I can assess my connectivity so that I can highlight disconnected components."
I added  island_nodes and connected_subgraphs to CandidateGraph, which will return a list of isolated nodes, and a list of sets that represent all the connected sub-graphs of the graph, respectively. 
I was sloppy with branching, so this also contains the changes for PR #35 and should be merged after.
=> Find disconnected graph components (JIRA #31) (Merge after PR #35)

autocnet/fileio/io_controlnetwork.py, autocnet/graph/network.py, functional_tests/test_three_image.py, functional_tests/test_two_image.py
I added the ability for **the graph** to produce a fromlist (and then later write it to a file), since the fromlist only cares about which images are included. Right now we start with an adjacency dict we turn into a graph, so we know that all nodes(images) should be included in the output fromlist. 
This is very simplistic, so please let me know if any of my above assumptions are wrong or anything else needs to be changed! We could later call this on a connected-subgraph to produce the fromlist for a connected subset of images.
=> Added ability to produce a fromlist (for isis) from the graph. References JIRA #83

autocnet/fileio/io_gdal.py, autocnet/graph/tests/test_network.py
This seems to be working, but I didn't test it very well (see my tests.)
latlon_extent is not used for Cubes right now. I added _pvl_header and _footprint_polygon to GeoDataset to support Cubes.
I'm not sure that reorganizing footprint_polygon.GetEnvelope() into the right shape for a bounding box is doing the right thing, so someone should double-check.
=> Basic 'calculate overlap' funcationality working* on cubes

autocnet/graph/edge.py
Basic example of running autopep8 on edge with only one aggressive argument and ignoring line length.
=> Pep8 example for --aggressive --ignore E501(line length)

autocnet/graph/network.py, autocnet/graph/tests/test_network.py
The mst in a Pandas DataFrame as a boolean mask. The DataFrame now an attribute of CandidateGraph.
=> Adding Minimum Spanning Tree Method to CandidateGraph

autocnet/graph/tests/test_network.py
This concerns a problem where the second mst graph in `TestGraphMasks`might have it's nodes slightly out of order after mst computation on rare occasions. This causes the node list comparison to fail even though node order is inconsequential.
=> fixed mst node comparison issue

autocnet/graph/tests/test_network.py
Changed the way I create the mst graph from edges to something cleaner. Changed `set` to `sorted`.
=> mst comapre issue: changed subgraph from edges and added sort compare

autocnet/fileio/io_gdal.py
It doesn't look like we actually need write permission, so I changed r -> r+
=> Fix for GeoDataset.foorprint failing on read-only cubes 

autocnet/graph/network.py, autocnet/graph/tests/test_network.py
Simple methods that filter through nodes or edges using some function and returns a sub-graph from matches. Mimics python's `filter` function.
=> simple node/edge filter

autocnet/fileio/io_utils.py, autocnet/graph/network.py, autocnet/graph/tests/test_network.py
This should give added robustness when dealing with polys that fail both the PVL and lat/lon check. Also added robustness when dealing with polys that pass the checks but still generate an invalid polygon. 
Calls to `match_features()` should no longer fail in the presence of isolated vertices.
=> added robustness to poor footprints

autocnet/graph/node.py, autocnet/matcher/feature_extractor.py, autocnet/matcher/tests/test_feature_extractor.py
for use outside of autocnet.  Now the extractor interface is standardized whether the underlying feature extractor is from vlfeat or opencv.
=> Generalize the feature extractor

autocnet/graph/node.py, autocnet/matcher/outlier_detector.py, autocnet/matcher/suppression_funcs.py, autocnet/matcher/tests/test_outlier_detector.py
This PR incorporates @acpaquette's changes in another PR and includes additional fixes to the spatial suppression check.  The essence of the fix is that the binary search space was far too granular and the correct cell size was never being selected because the discrete search space did not include it. 
The fix was to increase the granularity by an order of magnitude.  Not sure if this is a long term fix given the potential for images that are many orders of magnitude larger.  The alternative will be to rewrite the binary search to operate on a more continuous space; do not preallocate the search space.
=> Fixes Suppression

autocnet/graph/edge.py, autocnet/graph/network.py, autocnet/graph/tests/test_edge.py, autocnet/matcher/cpu_decompose.py, autocnet/matcher/cpu_matcher.py, autocnet/matcher/cuda_matcher.py
- overlap=bool param for Edge.get_keypoints(); Masks returned keypoints that aren't within their Node's MBR
- Edge.overlap_check() that populates Edge.masks["overlap"]; Masks matches whose keypoints aren't within their Node's MBR
- Unit tests for both of the above
=> "overlap" keypoint constraint & match mask

autocnet/__init__.py, autocnet/graph/edge.py, autocnet/matcher/cpu_matcher.py, autocnet/matcher/cuda_matcher.py, autocnet/matcher/tests/test_matcher.py
- cpu_matcher.match() & cuda_matcher.match() are static, take "edge" instead of self
- cpu_matcher.match() & cuda_matcher.match() reset Edge.masks to empty df
- matcher methods are patched in to static Edge._match(edge)
- member method Edge.match() calls static Edge._match(self)
- TestMatcher.test_cpu_match() adds coverage for cpu matcher
#191 and #192
=> cpu/cuda_matcher.match() is static & clears Edge.masks

autocnet/graph/network.py, autocnet/graph/tests/test_network.py
Fixed #217 to throw an error if the given node has no overlap with any of the other images. Also changed the output of compute_intersection to return a tuple of the overlaps_all geometry and then the intersection dataframe. Currently returns the overlaps_all geometry in a pandas dataframe which doesn't seem necessary.
=> Compute_Intersection Changes

.travis.yml, autocnet/control/control.py, autocnet/graph/edge.py, autocnet/graph/network.py, autocnet/graph/node.py, autocnet/graph/tests/test_edge.py, autocnet/graph/tests/test_network.py, autocnet/io/network.py, autocnet/matcher/tests/test_ciratefi.py, autocnet/matcher/tests/test_matcher.py, autocnet/utils/utils.py, bin/image_match.py, conftest.py, pytest.ini, tests/conftest.py, tests/test_save_load.py, tests/test_three_image.py, tests/test_two_image.py
This PR updates the API to networkX 2.0.  
Major changes:
`CandidateGraph.add_image` is intentionally commented out.  This method is going to need some thought before adding it back to the graph for working with the new API.
Otherwise, I tried to keep most of the changes centralized inside of network.  
I added backwards compatibility methods to the CandidateGraph that should not break our existing examples / docs.  These should be yielding out the node and edge objects in a way that previous users are expecting.  These are very lightly tested and could use some more robust testing (either inside of the graph or inside the 3 image functional test).
This PR also provides an example for porting standard unittest testing to PyTest and using fixtures / parametrization.  The ciratefi test has …
=> Updates to NetworkX2

README.rst
* In 3.6 days, the env install needs to specify that it needs to be a 3.5 env
* plio is not available in the given channels, so I added an install command that pulls it from the USGS channel
Fixes #241
=> Add required changes to installation instructions

README.rst
The addition of channels like menpo and conda-forge drastically change the dependency chain, so it's better to have these configurations only added for the newly created environment. This is achieved by adding the `--env` option to the `conda config` command.
Also, after adding the `usgs-astrogeology` channel, it's not required in the `install` command.
=> improving conda commands

environment.yml
Found this when setting up an env. This removes the `pip` warning.
=> Adds pip to the environment file to fix pip warning

sql/compute_overlapping_geometries.sql
This adds an ST_INTERSECT query to the inner query as a performance improvement. I believe that the query planner should use that WHERE statement first and then perform the actual intersections. This should take the inner query from best case n^2 to worst case n^2.
=> Performance improvement in sql overlap

autocnet/graph/node.py
This prevents failure when the JSON file cannot be written out. If there already exists a file, things can continue just fine, but if no file exists and one cannot be written, then the camera will throw an exception itself.
=> Added warning when json file cannot be written out

autocnet/graph/node.py, autocnet/io/db/model.py, autocnet/io/db/tests/test_model.py
Avoids strange errors later on about None type objects not having the required attributes for `from_shape`
=> Empty footprint

autocnet/graph/network.py
Right now, every time the ncg is created the intersection code is run. Using Kelvin's area the first run is ~500 polys. When I finally noticed this issue, I had >6k polys.
=> Fixes repeat calls to intersection code

autocnet/matcher/subpixel.py
This went from ~2500 points ignored to ~440 ignored. I have not visualized, but this PR is about the ability to subset the points.
Code that I used when testing:
```python
from autocnet.matcher.subpixel import cluster_subpixel_register_points
subpixel_template_kwargs = {'image_size':(111,111), 'template_size':(101,101)}
iterative_phase_kwargs = {'size': 71}  # Try a smaller size so that the point is able to move less. This should help on slivers since we have a better shot to get this area
filters = {'ignore':True} # Filter to only process those points that were ignored in the first phase
cluster_subpixel_register_points(iterative_phase_kwargs=iterative_phase_kwargs,
subpixel_template_kwargs=subpixel_template_kwargs, # Keep the template matcher strict
filters=filters)
```
and then snippet …
=> Adds ability to subpixel a subset of points

autocnet/graph/edge.py, autocnet/graph/network.py, autocnet/io/db/tests/test_model.py, autocnet/matcher/cross_instrument_matcher.py, autocnet/spatial/overlap.py, autocnet/transformation/spatial.py
pyproj.Proj class defaults to the -180 to 180 domain. Therefore, when pyproj.transform is called to preform the transformation using those classes the output is in the 180 domain. Instead of chasing down all instances of pyproj and inserting the lon_wrap=180 to set the domain to 360, I consolidated all pyproj calls to instead go through the already implemented reproject() function in autocnet and updated only the pyproj calls within reproject() with the lon_wrap keyword.
This pull request assumes that the images coming in are in the 360 domain!! A method should later be implemented where the projection domain for the points is determined by the domain of the input image (see issue #402 for current discussion on that topic)
=> Changing point projection domain from +/-180 to 0/360

autocnet/graph/node.py, autocnet/matcher/cpu_extractor.py, autocnet/spatial/overlap.py, bin/acn_overlaps
This fixes a few things.
* A bug where NetworkNodes tried to set the ignore column in the images table before they were added to the table.
* A parameter got re-named but the serial point placing code didn't get updated
* If the new "most interesting point" code doesn't find a feature it causes the entire run to fail
=> Various bug fixes

autocnet/graph/edge.py, autocnet/matcher/subpixel.py
#423 changed subpixel.subpixel_template to also return the correlation map. This just ignores that output where it gets called.
=> Accounted for extra output from template matcher

autocnet/matcher/subpixel.py, bin/acn_overlaps
As per previous group discussion, phase template matching works best on small areas. So I am switching the order under the assumption that naive template matching will get the registration close (or fail and then be ignored) and the phase template can do a final adjustment on a much smaller area.
=> Switching order of point registration

autocnet/matcher/subpixel.py, autocnet/matcher/tests/test_ciratefi.py, autocnet/matcher/tests/test_subpixel.py, autocnet/spatial/overlap.py, autocnet/spatial/tests/test_overlap_points.py, autocnet/transformation/roi.py, autocnet/transformation/tests/test_roi.py
See #426 for the related issue.
- Test updates to the subpixel_template, subpixel_phase, iterative_phase, and place_points_in_overlaps methods that make me much more comfortable that the code is behaving how we believe it is.
- Added an ROI object to (1) store the offsets that we need in subpixel shifting and overlap computation, (2) to make the returns cleaners, (3) to provide a place to implement warping, and (4) to, I think, make this more testable.
=> Fixes #426

autocnet/io/db/model.py, autocnet/matcher/subpixel.py, autocnet/spatial/overlap.py
Changes weights so that they are null before subpixel registration and after subpixel registration, reference measures have a weight of one while non-reference measures have a weight=cost func.
Sets a limit of the amount of jobs (per chunk) is sent to the cluster at one time. 
Additionally, if both phase and template matching pass, the new adjusted line sample should be the phase results (since my last PR #432).
=> minor bug fixes and weight value changes with Jays PR

autocnet/spatial/overlap.py
This was causing measures to be incorrectly reprojected from ground points.
=> Fixed a bug where planetographic lat/lon values were being passed to campt

autocnet/io/db/model.py, autocnet/matcher/subpixel.py, autocnet/spatial/isis.py, autocnet/spatial/overlap.py, bin/acn_overlaps
Contains a lot of small alterations:
- specifying pointid and outputing to subpixel logs, for easier debugging
- lowering the default size of iterative phase
- removing the catch all try excepts in matcher/subpixel.py
- raising errors in spatial/isis.py when point does not properly project to/from ground (exposing error keyword output by isis campt)
=> Explicit pointid, remove catch all try/excepts, adding isis point projection error handling

README.md, conftest.py
The PW for local testing is now 'NotTheDefault'. This should fix #376. The README has been updated. The conftest.py file now looks for the 'TRAVIS' env variable since travis defaults to a blank password (and it is way easier to add this check in our code base than to figure out what Travis will do with a PW change on the postgres user...)
=> Fixes 376 and uses non-default PW for local testing

autocnet/cg/cg.py, autocnet/graph/network.py
I was not seeing the same reference measures in my written out control network as I was seeing in the database. This was because the to_isis default query did not order the database the same way is done when subpixel registering points. So when plio is handed the unordered data frame, it just picks the first measure it gets per point for reference.
I updated the query to order by pointid and then measure id. My concern with this code update is now it assumes that you will hand it a query containing fields 'id' and 'pointid'. I feel like is necessary for the proper write out, but does limit what a user can do with the sql query line.
=> Making to_isis write out sql query ordered like subpixel register

autocnet/graph/network.py, autocnet/io/db/model.py
I was running into an issue where points were not being placed in overlaps. This was because I was using the 'new' method on CTX image overlaps with a large N/S extent and almost no E/W extent. 
I wanted to be able to place points into overlaps that did not already have points. When the config as refactored, calls to place_points_in_overlaps were replaced with an apply of place_points_in_overlap. The apply func on the network can take a filter kwarg. I started looking at how to pass the filter in for things like doing an inner join or applying a spatial function. Long story short, this would have resulted in a pretty crazy API where filters would need to define operators, external functions, functions on objects, etc. Not something to do.
So, this PR adds a query_string argument to the …
=> Adds support for apply with query and overlay points

autocnet/cg/cg.py, autocnet/graph/network.py, autocnet/io/db/tests/test_model.py, autocnet/matcher/cross_instrument_matcher.py, autocnet/matcher/subpixel.py, autocnet/transformation/roi.py
Most changes are small bug fixes, with the only new code implementation being a new ground point grid creation. 
Previously I tried to evaluate the most east/west cubes in an area to help create a slanted grid along the travel direction of the images. However, this most east/west cube evaluation was too vague and ended up being incorrect for the area I was grounding.
I replaced this code with a more robust method that calculates an affine transformation between two sets of points (envelope and minimum_rotated_rectangle) that are existing properties on the footprint object. It then lays down a normal grid and applies the affine transformation to get a grid with a track direction slant.
=> Necessary fixes discovered during grounded product creation

autocnet/graph/edge.py, autocnet/graph/network.py, autocnet/io/db/controlnetwork.py, autocnet/io/db/model.py, autocnet/matcher/cross_instrument_matcher.py, autocnet/spatial/overlap.py, autocnet/transformation/spatial.py, autocnet/transformation/tests/test_spatial.py
This allows us to select who many/which points to propagate from one network to another. This is particularly helpful when grounding a network. The initial propagate_control_network call can propagate a single point corresponding to the best match (as defined by geom_match output template metric) between a control network existing in the grounding data to the control data. Then the second propagate_control_network call can propagate that best point (now in the control data image space) to the rest of the overlapping control data images.
During this code change I also added doc strings to the propagation functions and reconciled the use of ographic/ocentric latitudes throughout the code. Autocnet now expects ocentric latitude inputs from the DB geometry columns.
=> Adding cost kwargs to propagate_control_network plus bug fix

autocnet/matcher/cross_instrument_matcher.py, autocnet/matcher/subpixel.py
Added doc strings to geom_match and subpixel_register_measure functions.
Additionally, while addressing the comments on PR #460, I swapped a raw sql query for an sqlalchemy query. This caused an error because the code was expecting a list return as opposed to an object.
=> Adding documentation to subpixel matchers and smalll bug fix for PR #460

docs/users/installation.rst
bigger issue is that
`> conda install -c jlaura autocnet-dev`
responds
`PackagesNotFoundError:`
=> typo, 'conda condig' should be 'conda config'

README.md
Regardless of the typo fix, these instructions do not seem to work.
upon following steps 2, 3, and 4 (`conda install -c usgs-astrogeology autocnet`)
I am unable to succesfully use autocnet. 
`> from autocnet.graph.network import NetworkCandidateGraph`  
returns this error  
```
~/anaconda3/envs/autocnet/lib/python3.7/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
"Distutils was imported before Setuptools. This usage is discouraged "
~/anaconda3/envs/autocnet/lib/python3.7/site-packages/pysis/env.py:31: RuntimeWarning: Could not find isis. Is `ISISROOT` set?
warnings.warn('Could not …
```
=> typo in conda install command

services/redis.conf
This should not be a CI tested change because I do not believe we use the services/docker-compose in the CI environment.
=> Explicitly sets the redis connection max

autocnet/matcher/subpixel.py, autocnet/spatial/overlap.py, bin/acn_submit
These changes ensure that the sessions are being closed properly. I tested this via a notebook. I need to think more about if/how this could be CI tested. Not sure it can be without some pretty significant mocking.
Here is the test I ran:
1. Create an NCG with 2 images
2. Get the current count of number of connections to the db using: 
```
def check_connection_count(ncg):
with ncg.session_scope() as session:
num_con = session.execute('SELECT sum(numbackends) FROM pg_stat_database;').scalar()
#num_con = session.execute('select count(*) from pg_stat_activity;').scalar()
return num_con
```
3. Confirm that the count is either 1 or 1+any pgadmin connections. To do this cleanly, I stood up a test_db container on smalls so that nothing was colliding with other people working.
4. Print the number …
=> Session cleanup

autocnet/graph/edge.py
This fixes costs so that they can be properly used. The change is needed so that one can run something similar to:
```python
for s, d, e in ncg.edges(data='data'):
e.network_to_matches()
if len(e.matches) < 1:
continue
e.compute_fundamental_matrix()
e.compute_fundamental_error()
print(e.costs)
break
```
=> Fixes costs to work within the session

autocnet/graph/edge.py, autocnet/graph/network.py, autocnet/graph/tests/test_edge.py, autocnet/graph/tests/test_network.py, autocnet/io/db/model.py, autocnet/utils/serializers.py, bin/acn_submit, conda/meta.yaml, environment.yml
This PR gets edges setup to be persistent into the DB. Once persistent in the DB, we can use the weights to do all kinds of different masking operations.
Examples:
```
def weight_func(edge):
edge.weights = ('byid', edge.source['node_id'] % 2)
return True
ncg.apply(weight_func, on='edge')
```
Here the arbitrary `weight_func` is being applied to every edge. Since we are applying to an edge, the first arg is the edge itself. Here we access the weights attribute (that is a dict under the hood) and use the setter to add or update the `byid` key with a value derived from the `node id` of the source node. Since the function in here runs on the edge, it can access anything that the edge can access and since the edge has a `parent` attribute that is the graph, that is basically everything.
So, we …
=> Adds arbitrary weights to the edges for use in then finding islands

autocnet/matcher/cross_instrument_matcher.py, autocnet/matcher/naive_template.py, autocnet/matcher/subpixel.py, autocnet/matcher/tests/test_subpixel.py, autocnet/transformation/roi.py
This PR alters the subpixel registration to use an affine transform that is centered on the ROI (instead of the upper left corner). I have a notebook that demos how this is working that I would be happy to show via a private gist link. 
I will comment inline if that helps though I tried to comment in the code directly so that the why is longer lived.
=> affine centered on the ROI

autocnet/graph/network.py, bin/acn_submit
This code change lets you pass an arbitrary iterable to the submission script that then has access to the ncg. For example:
```
iterable = [list_of_coordinates]
def simple(value, ncg=None):
print(ncg.config)
print(value)
ncg.apply(simple, on=valid_iterable)
```
It is then possible to apply the func over the arbitrary iterable while having access to the ncg. This is nice if say, we have an iterable of ground control point coordinates that we want to, in parallel, add to the database.
=> Adds arbitrary iterable submission

autocnet/graph/network.py, autocnet/graph/node.py, autocnet/io/db/model.py
'from_cnet' is a NCG class method which calls another class method 'from_filelist', however, 'from_filelist' then calls 'from_database' which is an instance method. This causes an error because it does not have access to 'self'. To fix this we created an intermediate function 'add_from_filelist' which holds the logic and 'from_filelist' just instantiates an NCG, attaches the config, and calls 'add_from_filelist'.
=> Fixing NetworkCandidateGraph.from_cnet()

environment.yml
The dev builds of travis are having an issue with their compilation flags causing symbols errors. Switching to the conda-forge version fixes this. Fixes #499
=> Removed dev label from usgscsm

docs/users/workshops/FY21_workshop/python_software_tutorial.ipynb
Somehow this line in the notebook got deleted and was causing parsing error when it was opened.
=> Fixed missing line in nb

README.md
Fixes #563.
Minor removal of a line in the test setup instructions that is not needed.
=> Removes unneeded postgis template instruction from README

.github/workflows/continuous_integration.yml, AUTHORS.rst, Makefile, README.md, autocnet/cg/change_detection.py, autocnet/cg/tests/test_change_detection.py, autocnet/matcher/cross_instrument_matcher.py, autocnet/matcher/ground.py, autocnet/matcher/subpixel.py, autocnet/spatial/isis.py, autocnet/spatial/overlap.py, autocnet/spatial/tests/test_isis.py, autocnet/utils/hirise.py, autocnet/utils/tests/test_hirise.py, bin/acn_cd, conda/meta.yaml, environment.yml, notebooks/blob_detection.ipynb, notebooks/hirise_registration.ipynb
* Converted everything I could find from *pysis* to *kalasiris*.
* Added tests for functions that used *kalasiris* in order to make sure I didn't screw anything up (fingers crossed).
* Added a Makefile with all kinds of functionality, but  specifically a "test-resources" target to download a pair of sample HiRISE files to run tests on.  If this directory isn't present, the tests that need them will be safely skipped.
* Reviewed the three functions in spatial/isis.py, and refactored them.
* They were inconsistently returning single values or a list, now, if given a single value, they'll return a two-tuple of singletons, if they are given a Sequence or a Numpy array, they'll return a two-tuple of Sequences or Numpy arrays, as appropriate.
* Coordinate order shall be: x then y, longitude …
=> Convert from pysis to kalasiris and rewrite of spatial/isis.py

autocnet/spatial/isis.py, autocnet/spatial/tests/test_isis.py
The `spatial/isis.py::image_to_ground()` function calls the `point_info()` function which just returns the results dictionary parsed from the PVL-text return of ISIS `mappt` or `campt`.  Turns out that while both return PVL-text with keys like `PlanetocentricLatitude` one of those ISIS programs returns just a plain numeric value, and the other returns a value and a unit.  To a PVL parser, those are different things, and one is returned as a `float` or `int` and the other is returned as a `pvl.collections.Quantity` object, from which the value can be extracted, but they are different kinds of objects, and `image_to_ground()` was not properly handling that duality.
Now it does.  More robust tests were added for image_to_ground() and ground_to_image(), just for good measure.
Would close …
=> image_to_ground fix

CHANGELOG.md, autocnet/spatial/isis.py, autocnet/spatial/tests/test_isis.py, autocnet/utils/utils.py, bin/acn_cd
This fixes #584, but making the kalasiris import optional. I solved this problem by wrapping the import in a try except. On the except, a FailedImport class is matched to the module name. Then any calls to the module using dot notation (that calls `__getattribute__` will raise an ImportError. This way, we can run any functions / methods in a file that do not use the import that failed.
To be even more explicit about what is happening is that kalasiris is attempting to import, but when the os.environ['ISISROOT'] call fails, the import raises. When that import raises, the except block in autocnet is triggered instantiating the FailedImport class.
I tested this in an interactive python session by importing autocnet.spatial.isis and then attempting to make use of an `isis.*` call. That module …
=> Fixes #584

autocnet/cg/change_detection.py, autocnet/cg/tests/test_change_detection.py, autocnet/utils/hirise.py
This PR catches two other Kalisiris imports that needed to be conditional and updates the change detection tests to support conditional imports of the ISIS dependency.
These fixes were needed to have a fully passing testing harness before starting work on a 1.0.0 release.
=> Missed Kalisiris imports fixed
