USGS-Astrogeology/autocnet

CONTRIBUTING.rst

I updated some incorrect URLs I found while working on updating tests.

Updated CONTRIBUTING.rst to have correct URLs.

---

functional_tests/test_two_image.py

This PR should stay open until the functional test, that measures progress for this sprint, is passing.

Functional test

---

.travis.yml
autocnet/fileio/io_gdal.py
autocnet/fileio/tests/test_io_gdal.py
autocnet/graph/network.py
autocnet/matcher/matcher.py
autocnet/matcher/tests/test_matcher.py

Reverts USGS-Astrogeology/autocnet#15

Revert "Revert "Matcher in place""

---

.travis.yml
autocnet/matcher/feature_extractor.py
autocnet/matcher/tests/test_feature_extractor.py
requirements.txt

Created feature_extractor and associated test

---

autocnet/examples/Apollo15/adjacency.json
autocnet/examples/Apollo15/two_image_adjacency.json
autocnet/graph/network.py
autocnet/graph/tests/test_network.py
functional_tests/test_two_image.py

Updated node attributes image_name and image_path to be prepended with current working directories if relative paths are given.

Added convenience methods to CandidateGraph class. Fixes JIRA AUTOCONG-72

---

autocnet/graph/network.py
autocnet/graph/tests/test_network.py
autocnet/matcher/feature_extractor.py
autocnet/matcher/subpixel.py
autocnet/matcher/tests/test_feature_extractor.py
autocnet/matcher/tests/test_subpixel.py
functional_tests/test_three_image.py
functional_tests/test_two_image.py

This PR fixes a regression where extraction parameters could not be specified via convenience functions, and moved template extraction for sub pixel matching to a stand alone function.

Offset validation

---

notebooks/AdaptiveNon-MaximalSuppressionDemonstration.ipynb

I just added a quick example notebook which shows a couple of images pre- and post- running ANMS (adaptive non-maixmal suppression,) so that we can demo this if we need to.

Added example notebook for ANMS

---

autocnet/cg/tests/test_cg.py
autocnet/control/control.py
autocnet/control/tests/test_control.py
autocnet/transformation/tests/test_transformations.py
autocnet/transformation/transformations.py
autocnet/vis/graph_view.py

The .py files within the CG, Control, Transformation, and Graph directories should be pep8 compliant aside from line length, imports not at top of file, and the boolean equivalency  checks.

Pep8 modifications 03/17/16

---

autocnet/transformation/transformations.py

Updated FundamentalMatrix.refine() docstring to better describe what FundamentalMatrix.refine() does.

Updated FundamentalMatrix.refine() docstring

---

autocnet/graph/tests/test_network.py

Reverts USGS-Astrogeology/autocnet#79

Revert "fixed mst node comparison issue"

---

autocnet/graph/network.py
autocnet/graph/tests/test_network.py

@Kelvinrr this one is for you.  I will be in the air until this afternoon, so I will not be able to make review changes until tonight.  If the review is minor stuff, go ahead comment and merge.  This way you can use the code.  If it is major hold off.  Wither way, I'll address comments after the flight.

Fixes subgraphs from node lists and add subgraph extract from edge lists

---

autocnet/graph/network.py

Renamed `func` to `function` in `apply_func_to_edges`'s parameter list.

changed the func

---

.travis.yml

This updates where packages are being pulled from.

Update to travis 

---

autocnet/graph/edge.py
autocnet/graph/node.py
image_match_config.yml

Also updated the image_match script to work without graph clean keys

Fixed unchanged handle variables to geodata variables

---

autocnet/graph/network.py
autocnet/graph/tests/test_network.py

This will hopefully fix the CandidateGragh.number_of_edges() issue mentioned on Gitter. Plus, make it marginally more efficient.
(I don't know why it is including all these extra commits)

CandidateGraph.Size() fix

---

autocnet/graph/edge.py
autocnet/graph/markov_cluster.py
autocnet/graph/network.py
autocnet/graph/node.py
autocnet/graph/tests/test_edge.py
autocnet/graph/tests/test_markov_cluster.py
autocnet/graph/tests/test_network.py
autocnet/graph/tests/test_node.py
autocnet/matcher/feature_extractor.py
autocnet/matcher/health.py
autocnet/matcher/matcher.py
autocnet/matcher/outlier_detector.py
autocnet/matcher/subpixel.py
autocnet/matcher/tests/test_feature_extractor.py
autocnet/matcher/tests/test_matcher.py
autocnet/matcher/tests/test_outlier_detector.py
autocnet/matcher/tests/test_subpixel.py

Reverted the changes to the line lengths. I forgot to ignore line length in the autopep8 command, along with the flake8 command.

Made both the graph and matcher directories pep8 complaint

---

docs/users/installation.rst

I will probably test this tutorial once we have the binstar setup. Hopefully this will also help work out the environmental problems on our systems.

Updated the installation instructions for anaconda and AutoCnet

---

docs/library/matcher/feature.rst
docs/library/matcher/naive_template.rst

forgot to update descriptions 

---

.travis.yml
autocnet/control/control.py
functional_tests/test_two_image.py

~~Trying to make travis work again. Seems to pass on Linux. MacOS is a pain because it takes 1 hour before the tests even start. Even then, often fails before using `.travis.yml`. Maybe some way to mimic the Travis test env locally?~~
Seems to be working, although it feels a bit hack-y

Make Travis Great Again

---

autocnet/graph/edge.py
autocnet/graph/tests/test_edge.py

Function on edge that returns keypoints for source or destination node

Edge keypoint function

---

autocnet/control/tests/test_control.py
autocnet/graph/edge.py
autocnet/graph/tests/test_edge.py

- Conditionals using Edge.matches were broken, updated to use isinstance(), determining whether Edge.matches is df or None
- There was a fundamental matrix lookup loop in Edge.masks(); Removed this, no longer necessary
- Lots of coverage updates to Edge
- control.py classes & their methods should now be completely covered

Code Coverage & Updates to Edge

---

autocnet/graph/network.py
autocnet/io/network.py
functional_tests/test_three_image.py
functional_tests/test_two_image.py
setup.py

This PR removes the to_isis tests from the functional testing as this functionality should be handled in another class (such as a ControlMediator).  This also should fix the intermittent issues being caused with serialization/deserialization and edge ordering.  Finally, looks like a removal of cyvlfeat as a mandatory dependency snuck in.  Minimal change to `setup.py`.

Updates for plio change

---

autocnet/graph/edge.py
autocnet/graph/network.py
autocnet/graph/tests/test_network.py

- Allows user to add an image to an existing graph
- Optional 'adjacency' arg that can be dict or json file: Without it, tries to calculate adjacency using footprints; Without footprints, adds the image as a disconnected Node on the graph
- Optional 'basepath' arg: User can provide full path to image w/o basepath, or image file name with basepath
- Optional 'apply_func' arg: User can provide a static method or list of static methods that take an edge as their argument; These function(s) will be applied to any new edges generated when adding the image
```
def extract_and_match(edge):
for n in [edge.source, edge.destination]:
n.extract_features(n.get_array(band=1), extractor_parameters={'nfeatures': 800})
edge.match()
edge.compute_overlap()
edge.overlap_check()
edge.symmetry_check() …
```

Added CandidateGraph.add_image()

---

docker/Dockerfile
docker/README.md
docker/environment.yml

Containerized Linux dev environment for autocnet

Added Dockerfile for autocnet environment

---

autocnet/graph/network.py
autocnet/graph/tests/test_network.py

Extends networkx.graph.add_node() and add_edge() to take image file names

Adds add_node() and add_edge() to CandidateGraph

---

autocnet/matcher/ciratefi.py

flipped use_perctile's default value

---

environment.yml

Only environment.yml changed, other files were already merged but github is not recognizing the changes

Adds ipykernel to environment.yml; fixes libpoppler version error

---

autocnet/graph/edge.py
autocnet/graph/network.py
autocnet/graph/node.py
autocnet/io/db/model.py
autocnet/io/db/tests/test_model.py
autocnet/spatial/overlap.py
environment.yml

This PR does a few things related to the DB. I want to also run the demo.ipynb notebook with these changes in a clean DB to see I have broken anything that is not being well tested at the moment. Changes are:
- Remove GeoAlchemy2 from all locations except the models
- Add setters/getters to the models to support shapely<->geoalchemy2 (to support above)
- Adds more db tests

Abstracts out geoalchemy to single place

---

autocnet/graph/edge.py
autocnet/graph/network.py

Fixes asynchronous edge communication to the cluster.
Fixes #311

Async acn_submit change

---

autocnet/graph/network.py
autocnet/io/db/tests/test_model.py

Initial addition of the jigsaw reingest. Tests incoming

Jigsaw Reingest

---

autocnet/graph/edge.py
autocnet/graph/node.py
bin/acn_overlaps

Updates a symmetry check to be similar to fundamental and ratio.
Made the NetworkNode use the new dem height.
Adds the appropriate GeoDataset import to the overlaps script.

All the, Small things

---

autocnet/cg/cg.py

This is a short term solution that removes a hard coded limiter on the number of points. This should get further refactored. I'll open an issue.

Changes the func that was making N/S point more dense

---

autocnet/graph/node.py

Fixed typo getting dem from config

---

autocnet/cg/cg.py
autocnet/cg/tests/test_cg.py

This PR exposes parameters to allow users to control the number of points in a given direction. The parameters are exposed as funcs where the defaults are the kwarg lambdas.
The doc string describes the logic of the funcs that can be passed. I also ported the unit test tests over to pytest and added a few more. I am see ~91% coverage on the cg stuff locally.

Exposes point funcs

---

autocnet/graph/network.py
autocnet/spatial/overlap.py
autocnet/spatial/tests/test_overlap_points.py
notebooks/server/Demo.ipynb
setup.py

Errors that probably have been seen previously and fixed locally. Mostly just adding ['data'] for source and destination images and fixing typos
Took out height parameter from ng.place_points_in_overlaps()

Bug fixes in Demo notebook and for Demo notebook

---

autocnet/graph/network.py
autocnet/graph/node.py
autocnet/io/db/model.py
autocnet/io/db/tests/test_model.py
autocnet/io/db/triggers.py
autocnet/spatial/overlap.py
config/sample.yml
config/test_config.yml

Updated points Table to store points in XYZ and provide a lat/lon representation.
This is going to force people to re-create their databases so they get the correct table and triggers.

Change Points to use XYZ in the DB and automatically update the lat, lon geom

---

autocnet/spatial/overlap.py
autocnet/spatial/tests/test_overlap_points.py

Previously this was taking a list of networkx nodes which resulted in the cluster code not working. I've tested this in both serial and parallel and got the same results.

Changed point overlap code to take a list of autocnet Nodes

---

autocnet/cg/cg.py
autocnet/graph/network.py
autocnet/graph/node.py
autocnet/graph/tests/test_network_graph.py
autocnet/io/db/tests/test_model.py
conftest.py

Mostly code from @jlaura and @acpaquette but with some bugs ironed out. Tests inbound, shouldn't be merged without them.

Added `from_cnet` code

---

autocnet/graph/network.py
autocnet/spatial/isis.py
autocnet/spatial/overlap.py
autocnet/spatial/tests/test_overlap_points.py

some fixes for demo.ipynb

---

conftest.py

Added check for number of connections for db tests

---

autocnet/graph/network.py
config/sample.yml
config/test_config.yml

Added target name to config and to_isis call

---

autocnet/graph/network.py
autocnet/spatial/overlap.py
autocnet/spatial/tests/test_overlap_points.py

Clears out the database when from_filelist is run. Also updates the iterative place_points_in_overlaps function to pass the camera type through.

Small Fixes

---

autocnet/spatial/overlap.py
autocnet/spatial/tests/test_overlap_points.py
bin/acn_overlaps

I also removed the DEM parameter since it is part of the config and accessible in place_points_in_overlap by importing it instead of passing it in from the calling functions.

Refactored iterative phase call from place_points_in_overlap

---

autocnet/graph/network.py
autocnet/graph/node.py
autocnet/io/db/model.py
autocnet/matcher/subpixel.py
autocnet/spatial/overlap.py

I AM A LIAR :smiling_imp: 
These are just fast changes, I would still love to add in a column that tracks the calls (and their kwargs) that massage the line and samples values of measures. That is just a little harder for me to figure out how to do.

leaky session fix, populating new columns in DB

---

autocnet/matcher/subpixel.py
autocnet/spatial/overlap.py

Adding a node exclusion option to cluster jobs

---

autocnet/matcher/subpixel.py

… subpixel registers in a given overlap. Also a small clean up of a redundant function return.

ensuring that that source image is consistent for all measure

---

autocnet/matcher/subpixel.py
bin/acn_subpixel

Also, a small one line typo fix

Adds ability to pass custom cost function to cluster_subpixel_register_points

---

autocnet/control/control.py
autocnet/graph/edge.py
autocnet/graph/network.py
autocnet/graph/tests/test_network.py
autocnet/io/network.py
conftest.py

Gets all test for autocnet passing!

General fix to autocnet

---

autocnet/graph/network.py
autocnet/graph/node.py
autocnet/graph/tests/test_network.py
autocnet/io/db/model.py
autocnet/io/db/tests/test_model.py
autocnet/io/db/triggers.py

Added ignore property to Nodes and added a db trigger to ignore all measures on an image when that image's node is ignored.
This does not ignore edges in "little autocnet"

Added ignore property to NetworkNodes

---

autocnet/graph/network.py

Added ignore check to network apply

---

autocnet/matcher/naive_template.py
autocnet/matcher/subpixel.py
autocnet/matcher/tests/test_naive_template.py

Center of gravity based subpixel matcher. Working on tests now.

:construction:  Algorithm in, working on tests 

---

autocnet/matcher/cross_instrument_matcher.py
autocnet/matcher/naive_template.py
autocnet/matcher/subpixel.py
autocnet/matcher/tests/test_naive_template.py
autocnet/matcher/tests/test_subpixel.py
autocnet/spatial/isis.py

Added a matcher into cross_instrument_matcher.py (only left there as it is still tightly coupled to other functions in that module). Still untested and sorta jank, this is more to get in other peoples' hands to use.

geom matcher added

---

autocnet/graph/network.py
autocnet/spatial/overlap.py

Missed a self between initial implementation and changes for review.

Fixes bug from config

---

autocnet/graph/network.py
autocnet/io/db/model.py
autocnet/matcher/subpixel.py
autocnet/spatial/overlap.py

This is meant to be used for creating effective measure elimination metric based on its associated matching information. DO NOT MERGE

Adding template and phase match metrics and shifts to DB

---

autocnet/cg/change_detection.py
autocnet/graph/edge.py

Still not sure if Autocnet is the best place for this. On one hand it fits autocnet's functionality very well, but on the other hand, it has nothing to do with generating cnets. I am hesitant to start a new repo/project. I am open to suggestions if people feel this should be moved elsewhere. 
@jlaura thoughts?

Added modified change detection algorithm

---

autocnet/cg/change_detection.py
notebooks/blob_detection.ipynb

Prototype blob_detector functionality.
Currently returns 2 arrays -- one for "type 1 changes" and one for "type 2 changes."  One is "there used to be a feature in this location, now there is not," and the other is "there didn't used to be a feature here, but now there is."  This still needs to be better documented in the code, but I'm having trouble identifying which is which, particularly due to the fact that it is dependent on the order of images.   Documentation updates will be included in later commits.
Another important note is that the logic only allows for sub solar azimuth for one image (or a scalar to be used for the entire image), but the azimuth values are almost certainly different between images.  I'm not sure how to account for this.
There's one "readable" list comprehension …

Initial blob_detector function

---

autocnet/cg/change_detection.py
notebooks/blob_detection.ipynb

Adjusted parameters based on results from parameterization comparison notebook (which is too large to create a gist) and added an additional image func.

Adjusted parameters and added image_diff_squared 

---

autocnet/matcher/cross_instrument_matcher.py
autocnet/matcher/subpixel.py
config/demo.yml

Not sure if this should get pulled into the code base, just posting it for the new visualization code

New visualizations for geom_match

---

.travis.yml
autocnet/graph/tests/test_network_graph.py
autocnet/io/db/tests/test_controlnetwork.py
autocnet/io/db/tests/test_model.py
conftest.py
environment.yml

Updating travis to build on MacOS

---

autocnet/graph/network.py
autocnet/matcher/subpixel.py

Mostly Addresses issue #453, with some additional smaller ease of use fixes

Bug Fixes (Issue #453)

---

autocnet/spatial/overlap.py

@ladoramkershner This is the code that we just checked out together.

Adds place_points_in_image

---

autocnet/cg/cg.py
autocnet/graph/edge.py
autocnet/graph/network.py
autocnet/io/db/controlnetwork.py
autocnet/matcher/subpixel.py
autocnet/spatial/overlap.py
bin/acn_submit

This is a bit of a mixed bag PR, just hings I have implimented while working on the current product workflow:
- Adding image functionality for cluster apply 
- Renaming some vague variable names in subpixel_register_measure
- null_measure_ignore function (do we want to keep this after chip validity check?)
- adds log_dir specifically for cluster apply jobs, allows for easy organization of logs (VERY convenient)
- outlier rejection based on measure shift on edges class
- adds filter kwarg to edge's measure property (there is still issue #495 with this property)
- expanded find_side to work with MultiPolygons as well

'Convenience of Life' functions and kwargs

---

docs/users/workshops/FY21_workshop/autocnet_intro.ipynb
docs/users/workshops/FY21_workshop/jupyterhub_ipython.ipynb
docs/users/workshops/FY21_workshop/network_generation.ipynb

These are by no means done or even rough drafts. I just wanted everyone to have access to a consolidated folder!

file for workshop notebooks; start of a few notebooks

---

autocnet/matcher/cross_instrument_matcher.py

Looks like it should be as simple as this to resolve #510, as far as I can tell the data is right there in propagate_point it just needed to get passed through. Haven't been able to test due to an environment problem I'm having with the pyproj library

populate template metric (not tested)

---

autocnet/cg/change_detection.py

Adds functions to generate a random smattering of boulders over a given dem

Boulder gen

---

docs/users/workshops/FY21_workshop/plio_analysis.ipynb

This has most everything in it. I'm still working on the covariance transformation and maybe doing some proper weighting in the final radii solution using the radius sigmas.

First draft of PLIO notebook

---

autocnet/cg/change_detection.py

Fixes a problem where the boulder generation polys did not line up with DEM.

Boulder shift fix

---

autocnet/cg/change_detection.py
environment.yml

Adds the ability to generate an affine matrix and it's subsequent delta matrix. These can be applied to copies of a dem to moc a bad image registration.
This PR also updates the grayscale parameter to avoid checking the same variable more often than necessary.

Affine and Grayscale update

---

autocnet/graph/network.py
autocnet/io/db/controlnetwork.py
autocnet/io/db/model.py
autocnet/spatial/overlap.py

update the doc strings in spatial.overlap and added a kwarg for filling out the point's "identifier" field when laying down the points using either place_points_in_overlap or place_points_in_image

initial commit for variable pointid

---

docs/users/workshops/FY21_workshop/python_software_tutorial.ipynb

I made a few last minute changes to my part of the workshop.  I also checked for spelling and deleted all the answers from the exercises.

final edits for workshop

---

docs/users/workshops/FY21_workshop/network_generation.ipynb

Work actually done by @ladoramkershner

Final network generation notebook

---

autocnet/graph/edge.py
autocnet/graph/network.py
autocnet/graph/tests/test_edge.py
autocnet/graph/tests/test_network_graph.py
autocnet/io/db/controlnetwork.py
autocnet/io/db/tests/test_controlnetwork.py
autocnet/io/db/tests/test_model.py
autocnet/matcher/cpu_outlier_detector.py
autocnet/matcher/tests/test_outlier_detector.py
autocnet/matcher/tests/test_subpixel.py
conftest.py
setup.py
tests/test_save_load.py
tests/test_two_image.py

Comments are inline. The goal here was to get the update from jigsaw in. For Valles Marineris (sp?) it take ~120 seconds to update the 1.5M measures.
As a secondary goal, I tried to fix as many tests as possible. The two integration tests are still failing and can be fixed in a different PR.

Adds update from jigsaw and fixes rotted tests.

---

autocnet/matcher/subpixel.py
autocnet/matcher/tests/test_subpixel.py
environment.yml

Tried to keep the implementation as simple as possible to make it easier to copy+paste into whatever way we refactor subpixel,py

Added Fourier Mellen registration func

---

conda/meta.yaml
environment.yml
setup.py

Fixes #568.
A bunch of those imports are a surprise to me. Legacy of old stuff, etc. That doesn't matter though! So, PVL is added back in. Looking at the code, this should be fine as a straight insert of PVL 1.0. The usage is almost always ISIS cubes.

PVL does exist

---

autocnet/transformation/fundamental_matrix.py
autocnet/transformation/tests/test_fundamental_matrix.py

Only file that needed to be changed to use logging was `fundamental_matrix.py`

updated transformation module to use logging

---

autocnet/spatial/overlap.py

I converted the few warning statements that were in the `overlap.py` file, there weren't any test's for this file and the other two files in this module didn't seem to using warnings at all. I'm wondering if it would be worth it to create a `test_overlap.py` file to test the logging and possibly the rest of the code in this file.

converted spatial module to use logging

---

autocnet/matcher/ciratefi.py
autocnet/matcher/cpu_matcher.py
autocnet/matcher/cpu_outlier_detector.py
autocnet/matcher/cross_instrument_matcher.py
autocnet/matcher/cuda_extractor.py
autocnet/matcher/cuda_matcher.py
autocnet/matcher/ground.py
autocnet/matcher/subpixel.py
autocnet/matcher/tests/test_ciratefi.py
autocnet/matcher/tests/test_matcher.py
autocnet/matcher/tests/test_outlier_detector.py
autocnet/matcher/tests/test_subpixel.py

This might be a longer pr as I did all of the matcher module's files in one go. I also added logging in several places where we are raising a value error. I can remove them if it's unneeded but I was thinking it would be good to log anytime a value error occurs.

Logging for matcher module
